name: CI

# Controls when the workflow will run
# Events that will be trigge this action/workflow
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get the most recent code in this github repository
      - uses: actions/checkout@v3
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 14
          
      - name: Install Dependences
        run: yarn
        
      - name: Build
        run: yarn build
        
      - name: Send build to aws ec2 instance
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules" # we add this sintax: !name_file to ignore this file when send the code
          target: "~/app/rentalx"
      
      

